version: '3.8'

services:
  # ------------------------------------
  # 1. Serviço de Banco de Dados (PostgreSQL)
  # ------------------------------------
  db:
    image: postgres:15-alpine
    container_name: guardian_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-guardiaodb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend

  # ------------------------------------
  # 2. Serviço de Cache (Redis / ElastiCache Mock)
  # ------------------------------------
  cache:
    image: redis:7-alpine
    container_name: guardian_redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379" # Exposto apenas para depuração local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - backend

  # ------------------------------------
  # 3. Serviço de Backend API (Go)
  # ------------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardian_api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-guardiaodb}?sslmode=disable
      REDIS_ADDR: cache:6379
      REDIS_PASSWORD: ""
      GO_ENV: production
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  # ------------------------------------
  # 4. Serviço de Worker (Go - Processamento Assíncrono)
  # ------------------------------------
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardian_worker
    restart: on-failure
    entrypoint: ["/app/worker"]
    environment:
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-guardiaodb}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

# ------------------------------------
# Configurações de Volumes e Rede
# ------------------------------------
volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
