services:
  api:
    env_file: ./.env.e2e
    ports:
      - "18080:8080"
    environment:
      PORT: 8080
      # Para testes no navegador
      CORS_ORIGINS: "http://localhost:3000,https://localhost:3000"

  worker:
    env_file: ./.env.e2e
    environment:
      WORKER_ENABLE_MOCK: "true"

  # db e cache já vêm do compose base (docker/docker-compose.yml)