# Build stage
FROM golang:1.24-alpine AS build
WORKDIR /app
RUN apk add --no-cache git ca-certificates tzdata

# Ajudar o Go a pegar a toolchain exata se precisar (ex.: 1.24.x)
ENV GOTOOLCHAIN=auto
ENV CGO_ENABLED=0

# Cache de dependências
COPY go.mod go.sum ./
RUN go mod download

# Copia o restante do código
COPY . .

# Build do binário
RUN go build -o /app/server ./cmd/api

# Runtime stage (distroless)
FROM gcr.io/distroless/base-debian12
WORKDIR /app

# CA certs (TLS)
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Binário
COPY --from=build /app/server /app/server

# Porta usada pela app
ENV PORT=8080
EXPOSE 8080

USER nonroot:nonroot
ENTRYPOINT ["/app/server"]