name: E2E

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Build and start E2E stack
        run: |
          make e2e-up
          # aguarda já é feito pelo alvo e2e-test, mantemos aqui só a subida

      - name: Run E2E tests
        env:
          E2E_BASE_URL: http://localhost:18080/api/v1
        run: |
          make e2e-test

      - name: Dump E2E logs if failed
        if: failure()
        run: |
          make logs-e2e

      - name: Tear down E2E stack
        if: always()
        run: |
          make e2e-down